query ($uid: Int) {
    MediaListCollection(userId: $uid, type:ANIME) {
        lists {
            name
            status
            entries {
                progress
                updatedAt
                media {
                    id
                }
            }
        }
    }
}
